version: '3.1'

services:

  mysql:
    image: mysql:8.0 # Joomla 5 needs >= 8.0.13, actual 8.1.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: example12345678
    volumes:
      - ./joomla-backup:/docker-entrypoint-initdb.d
    networks:
      - joomla-network

  mysqladmin:
    container_name: test_joomla_mysqladmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "3082:80"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - joomla-network

  joomla-test.local:
    container_name: test_joomla_local
    build: .
    restart: unless-stopped
    ports:
      - 3081:80
    environment:
      JOOMLA_SITE_NAME: "Joomla Test Site"
      JOOMLA_ADMIN_USER: "Admin Tester"
      JOOMLA_ADMIN_USERNAME: admin
      JOOMLA_ADMIN_PASSWORD: admin12345678
      JOOMLA_ADMIN_EMAIL: admin@example.com
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: example12345678
      JOOMLA_DB_NAME: joomla
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
      RESTORE: ${RESTORE}
      ROOT: ${ROOT}
    volumes:
      - .:${ROOT}
      - ./joomla-backup:/var/www/html/joomla-backup
      # - ./joomla-data:/var/www/html
    depends_on:
      - mysql
    networks:
      - joomla-network

  cypress:
    container_name: test_joomla_cypress_local
    image: cypress/included:12.8.1 # actual 13. + Chrome 116. + Edge 116. + Firefox 117.
    restart: "no"
    entrypoint: ${ROOT}/scripts/exec-cypress.sh
    ports:
      - 3080:80
    depends_on:
      - joomla-test.local
    environment:
      CYPRESS_BASE_URL: "http://joomla-test.local"
      DISPLAY:
      JOOMLA_USERNAME: ${USERNAME}
      JOOMLA_PASSWORD: ${PASSWORD}
      ROOT: ${ROOT}
    volumes:
      - .:${ROOT}
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /cypress-test/tests
    networks:
      - joomla-network

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 3083:1080

networks:
  joomla-network: